import { motion } from "framer-motion";
import { Button } from "@/components/ui/button";
import { FileText, PieChart, TrendingDown, ClipboardList, Download } from "lucide-react";

const reports = [
  { icon: FileText, title: "Carbon Footprint Report", desc: "Comprehensive breakdown of your total emissions across all scopes." },
  { icon: PieChart, title: "Scope Analysis Breakdown", desc: "Detailed analysis of Scope 1, 2 and 3 emission sources." },
  { icon: TrendingDown, title: "Reduction Roadmap", desc: "Actionable plan with timelines and reduction targets." },
  { icon: ClipboardList, title: "ESG Summary Report", desc: "Board-ready ESG summary aligned with global frameworks." },
];

const ReportsSection = () => {
  return (
    <section id="reports" className="section-padding bg-muted/40">
      <div className="section-container">
        <motion.div
          className="text-center mb-16"
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
        >
          <h2 className="text-3xl sm:text-4xl font-display font-bold text-foreground mb-4">
            Sample Sustainability Reports
          </h2>
          <p className="text-muted-foreground max-w-lg mx-auto">
            See the quality and depth of reports generated by ClimeScore.
          </p>
        </motion.div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 mb-12">
          {reports.map((r, i) => (
            <motion.div
              key={r.title}
              className="card-elevated card-hover p-6 text-center"
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.1 }}
            >
              <div className="w-14 h-14 rounded-2xl bg-accent flex items-center justify-center mx-auto mb-4">
                <r.icon className="text-primary" size={26} />
              </div>
              <h3 className="font-display font-semibold text-foreground mb-2">{r.title}</h3>
              <p className="text-xs text-muted-foreground">{r.desc}</p>
            </motion.div>
          ))}
        </div>

        <div className="text-center">
          <Button variant="hero" size="lg">
            <Download size={16} className="mr-2" /> Download Sample Report
          </Button>
        </div>
      </div>
    </section>
  );
};

export default ReportsSection;
