import { motion } from "framer-motion";
import { Button } from "@/components/ui/button";
import { FileText, PieChart, TrendingDown, ClipboardList, Download } from "lucide-react";
import { useState } from "react";



const reports = [
  { icon: FileText, title: "Carbon Footprint Report", desc: "Comprehensive breakdown of your total emissions across all scopes." },
  { icon: PieChart, title: "Scope Analysis Breakdown", desc: "Detailed analysis of Scope 1, 2 and 3 emission sources." },
  { icon: TrendingDown, title: "Reduction Roadmap", desc: "Actionable plan with timelines and reduction targets." },
  { icon: ClipboardList, title: "ESG Summary Report", desc: "Board-ready ESG summary aligned with global frameworks." },
];

const ReportsSection = () => {
  const [open, setOpen] = useState(false);
const [name, setName] = useState("");
const [org, setOrg] = useState("");
const [email, setEmail] = useState("");
const [comment, setComment] = useState("");


  const handleSubmit = (e) => {
  e.preventDefault();

  const subject = encodeURIComponent("Request for ClimeScore Sample Report");

  const body = encodeURIComponent(
`Name: ${name}
Organization: ${org}
Email: ${email}
Comment: ${comment}`
  );

  const gmailLink = `https://mail.google.com/mail/?view=cm&fs=1&to=gautam@nettzero.world&su=${subject}&body=${body}`;

  window.open(gmailLink, "_blank");

  setOpen(false);
};
  return (
    <section id="reports" className="section-padding bg-muted/40">
      <div className="section-container">
        <motion.div
          className="text-center mb-16"
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
        >
          <h2 className="text-3xl sm:text-4xl font-display font-bold text-foreground mb-4">
            Sample Sustainability Reports
          </h2>
          <p className="text-muted-foreground max-w-lg mx-auto">
            See the quality and depth of reports generated by ClimeScore.
          </p>
        </motion.div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 mb-12">
          {reports.map((r, i) => (
            <motion.div
              key={r.title}
              className="card-elevated card-hover p-6 text-center"
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.1 }}
            >
              <div className="w-14 h-14 rounded-2xl bg-accent flex items-center justify-center mx-auto mb-4">
                <r.icon className="text-primary" size={26} />
              </div>
              <h3 className="font-display font-semibold text-foreground mb-2">{r.title}</h3>
              <p className="text-xs text-muted-foreground">{r.desc}</p>
            </motion.div>
          ))}
        </div>

          <div className="text-center">
  <Button variant="hero" size="lg" onClick={() => setOpen(true)}>
    <Download size={16} className="mr-2" />
    Download Sample Report
  </Button>
</div>
      </div>
      {open && (
  <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">

    <div className="bg-white rounded-xl p-6 w-[420px] relative shadow-lg">

      <button
        onClick={() => setOpen(false)}
        className="absolute top-3 right-3 text-gray-500 hover:text-black"
      >
        ✕
      </button>

      <h2 className="text-xl font-semibold mb-4">
        Request Sample Report
      </h2>

      <form onSubmit={handleSubmit} className="space-y-4">

        <input
          type="text"
          placeholder="Your Name"
          required
          value={name}
          onChange={(e) => setName(e.target.value)}
          className="w-full border px-3 py-2 rounded-md"
        />

        <input
          type="text"
          placeholder="Organization Name"
          required
          value={org}
          onChange={(e) => setOrg(e.target.value)}
          className="w-full border px-3 py-2 rounded-md"
        />

        <input
          type="email"
          placeholder="Email Address"
          required
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          className="w-full border px-3 py-2 rounded-md"
        />

        <textarea
          placeholder="Comment"
          value={comment}
          onChange={(e) => setComment(e.target.value)}
          className="w-full border px-3 py-2 rounded-md"
        />

        <button
          type="submit"
          className="w-full bg-green-600 text-white py-2 rounded-md hover:bg-green-700"
        >
          Send Request
        </button>

      </form>

    </div>

  </div>
)}
    </section>
  );
};

export default ReportsSection;
