import React from "react";

const AgreementPage: React.FC = () => {

const containerStyle: React.CSSProperties = {
maxWidth: "1000px",
margin: "40px auto",
padding: "40px",
fontFamily: "Arial, sans-serif",
lineHeight: "1.7",
background: "#ffffff",
color: "#333",
borderRadius: "8px",
boxShadow: "0 6px 20px rgba(0,0,0,0.08)"
};

const sectionTitle: React.CSSProperties = {
color: "#2f855a",
marginTop: "40px"
};

const heading: React.CSSProperties = {
fontWeight: "bold",
marginTop: "20px"
};

return (

<div style={{background:"#f4f7f5", minHeight:"100vh", padding:"40px"}}>

<div style={containerStyle}>

<h1 style={{color:"#2f855a"}}>CLIMESCORE PLATFORM</h1>

<h2>SOFTWARE LICENSE AND USER AGREEMENT</h2>

<p>
This Software License and User Agreement (“Agreement”) is entered into between:
</p>

<p>
NettZero Environmental Advisory Technologies Private Limited, a company incorporated under the Companies Act, 2013, having its registered office at 1230, Hubtown Solaris, Andheri (East), Mumbai – 400069, India (hereinafter referred to as “NettZero”, “Company”, “Licensor”, or “ClimeScore”),
</p>

<p>
AND
</p>

<p>
The individual, organization, company or entity registering to access or use the ClimeScore platform (hereinafter referred to as the “User”, “Customer”, or “Licensee”).
</p>

<p>
By registering, accessing, or using the ClimeScore platform, the User agrees to be bound by the terms and conditions set forth in this Agreement.
</p>


<h3 style={sectionTitle}>1. DEFINITIONS</h3>

<p style={heading}>1.1 “Platform”</p>
<p>
means the ClimeScore software platform, website, applications, databases, analytical tools, dashboards, and related services made available by NettZero.
</p>

<p style={heading}>1.2 “Services”</p>

<ul>
<li>greenhouse gas emissions measurement</li>
<li>emissions analytics</li>
<li>sustainability reporting</li>
<li>emissions reduction insights</li>
<li>integration with carbon credit marketplaces</li>
<li>sustainability benchmarking tools</li>
</ul>

<p style={heading}>1.3 “GHG Emissions”</p>

<ul>
<li>GHG Protocol</li>
<li>IPCC emission factors</li>
<li>ISO 14064 frameworks</li>
<li>other recognized sustainability reporting standards</li>
</ul>

<p style={heading}>1.4 “User Data”</p>
<p>
means all information, operational inputs, data, documents, measurements, metrics, or files uploaded or entered into the Platform by the User.
</p>

<p style={heading}>1.5 “Output Data”</p>
<p>
means emissions calculations, reports, analytics, dashboards, charts or other information generated by the Platform using User Data.
</p>

<p style={heading}>1.6 “Subscription”</p>
<p>
means the paid license granted to the User for access to the Platform.
</p>


<h3 style={sectionTitle}>2. GRANT OF LICENSE</h3>

<p>
Subject to compliance with this Agreement, NettZero grants the User a non-exclusive, non-transferable, revocable, limited license to access and use the ClimeScore Platform solely for the purpose of:
</p>

<ul>
<li>measuring greenhouse gas emissions</li>
<li>analysing environmental impact</li>
<li>generating sustainability reports</li>
<li>supporting internal ESG and sustainability management</li>
</ul>

<p>
The license is granted only for the duration of the User’s active subscription.
</p>


<h3 style={sectionTitle}>3. PLATFORM ACCESS AND USE</h3>

<ul>
<li>enter operational data</li>
<li>calculate emissions</li>
<li>generate sustainability reports</li>
<li>monitor emissions across facilities or operations</li>
<li>access analytical dashboards</li>
</ul>

<p>The User shall not:</p>

<ul>
<li>reverse engineer the Platform</li>
<li>copy or replicate the software</li>
<li>sublicense or redistribute the Platform</li>
<li>use the Platform to provide competing services</li>
</ul>


<h3 style={sectionTitle}>4. USER RESPONSIBILITIES</h3>

<ul>
<li>the accuracy of all data entered into the Platform</li>
<li>ensuring operational information is correct</li>
<li>maintaining documentation supporting data inputs</li>
<li>compliance with applicable environmental regulations</li>
</ul>

<p>
NettZero shall not be responsible for errors resulting from incorrect or incomplete User Data.
</p>


<h3 style={sectionTitle}>5. EMISSIONS CALCULATION METHODOLOGY</h3>

<ul>
<li>GHG Protocol Corporate Standard</li>
<li>IPCC emission factors</li>
<li>industry emission databases</li>
<li>scientific literature and sustainability reporting frameworks</li>
</ul>

<p>
NettZero reserves the right to update calculation models and emission factors to reflect the latest accepted methodologies.
</p>


<h3 style={sectionTitle}>6. REPORTING AND DISCLOSURE</h3>

<ul>
<li>the Platform does not constitute a regulatory certification body</li>
<li>emissions reports generated are informational tools</li>
<li>Users remain responsible for regulatory disclosures and compliance</li>
</ul>


<h3 style={sectionTitle}>7. CARBON CREDIT INTEGRATION</h3>

<ul>
<li>price stability of carbon credits</li>
<li>regulatory acceptance of specific credits</li>
<li>financial performance of credit investments</li>
</ul>

<p>
Users must independently evaluate carbon credit purchases.
</p>


<h3 style={sectionTitle}>8. DATA RIGHTS AND OWNERSHIP</h3>

<ul>
<li>process User Data</li>
<li>analyse aggregated data</li>
<li>improve Platform algorithms</li>
<li>develop anonymized industry insights</li>
</ul>

<p>
NettZero may publish aggregated and anonymized environmental statistics derived from platform data.
</p>


<h3 style={sectionTitle}>9. DATA SECURITY</h3>

<p>
NettZero shall implement reasonable technical and organizational measures to protect User Data.
</p>


<h3 style={sectionTitle}>10. PLATFORM AVAILABILITY</h3>

<ul>
<li>maintenance</li>
<li>upgrades</li>
<li>technical issues</li>
<li>third-party service dependencies</li>
</ul>


<h3 style={sectionTitle}>11. CONSULTING SERVICES</h3>

<ul>
<li>sustainability strategy</li>
<li>carbon neutrality planning</li>
<li>emissions audits</li>
<li>ESG advisory</li>
</ul>


<h3 style={sectionTitle}>12. SUBSCRIPTION FEES</h3>

<ul>
<li>subscription plan</li>
<li>number of facilities or properties</li>
<li>data volume</li>
<li>additional services</li>
</ul>


<h3 style={sectionTitle}>13. INTELLECTUAL PROPERTY</h3>

<ul>
<li>software code</li>
<li>algorithms</li>
<li>databases</li>
<li>analytical models</li>
<li>visual dashboards</li>
</ul>


<h3 style={sectionTitle}>14. LIMITATION OF LIABILITY</h3>

<ul>
<li>indirect damages</li>
<li>consequential damages</li>
<li>loss of profits</li>
<li>regulatory penalties</li>
<li>investment losses related to carbon markets</li>
</ul>


<h3 style={sectionTitle}>15. TERMINATION</h3>

<ul>
<li>violates this Agreement</li>
<li>fails to pay subscription fees</li>
<li>engages in unlawful activity</li>
</ul>


<h3 style={sectionTitle}>16. MODIFICATIONS TO PLATFORM</h3>

<ul>
<li>update software features</li>
<li>modify calculation models</li>
<li>improve analytics tools</li>
</ul>


<h3 style={sectionTitle}>17. GOVERNING LAW</h3>

<p>
This Agreement shall be governed by and construed in accordance with the laws of India.
</p>

<p>
Any disputes shall be subject to the exclusive jurisdiction of the courts located in Mumbai, India.
</p>


<h3 style={sectionTitle}>18. ACCEPTANCE OF TERMS</h3>

<ul>
<li>have read this Agreement</li>
<li>understand its terms</li>
<li>agree to be legally bound by it</li>
</ul>


<h2 style={sectionTitle}>CLIMESCORE PRIVACY POLICY</h2>

<p>Effective Date: [Insert Date]</p>

<p>
This Privacy Policy describes how NettZero Environmental Advisory Technologies Private Limited (“NettZero”, “ClimeScore”, “we”, “our”, or “us”) collects, uses, processes, and protects information obtained from users of the ClimeScore platform and website.
</p>

<h3 style={sectionTitle}>1. INFORMATION WE COLLECT</h3>

<p style={heading}>1.1 Account Information</p>

<ul>
<li>Name</li>
<li>Email address</li>
<li>Phone number</li>
<li>Organisation name</li>
<li>Industry category</li>
<li>Billing information</li>
</ul>

<p style={heading}>1.2 Operational Data</p>

<ul>
<li>energy consumption</li>
<li>fuel usage</li>
<li>facility information</li>
<li>logistics data</li>
<li>waste management data</li>
<li>procurement information</li>
<li>supplier details</li>
</ul>

<p style={heading}>1.3 Sustainability and Environmental Data</p>

<ul>
<li>carbon emissions data</li>
<li>sustainability indicators</li>
<li>emissions reduction data</li>
<li>reporting metrics</li>
</ul>

<p style={heading}>1.4 Technical Information</p>

<ul>
<li>IP address</li>
<li>browser type</li>
<li>device information</li>
<li>usage analytics</li>
<li>login activity</li>
</ul>

<p style={heading}>1.5 Payment Information</p>

<p>
Payments may be processed through third-party payment processors. We do not store credit card numbers on our servers.
</p>


<h2 style={sectionTitle}>DATA PROCESSING AGREEMENT (DPA)</h2>

<h3 style={sectionTitle}>1. PARTIES</h3>

<p>
NettZero Environmental Advisory Technologies Private Limited (“Data Processor”)
</p>

<p>
The organisation using the ClimeScore platform (“Data Controller”).
</p>

<h3 style={sectionTitle}>2. PURPOSE OF DATA PROCESSING</h3>

<ul>
<li>calculating greenhouse gas emissions</li>
<li>generating sustainability reports</li>
<li>operating the ClimeScore platform</li>
<li>providing analytics services related to emissions</li>
</ul>


<h2 style={sectionTitle}>CARBON ACCOUNTING METHODOLOGY & DISCLAIMER</h2>

<p>Effective Date: [Insert Date]</p>

<p>
This Carbon Accounting Methodology and Disclaimer describes the principles, standards, data sources and limitations used by the ClimeScore Platform in measuring, estimating and reporting greenhouse gas emissions.
</p>

<h3 style={sectionTitle}>1. PURPOSE OF THE PLATFORM</h3>

<ul>
<li>measuring greenhouse gas emissions</li>
<li>analysing environmental impacts</li>
<li>identifying emission reduction opportunities</li>
<li>generating sustainability and ESG reports</li>
</ul>

<h3 style={sectionTitle}>2. METHODOLOGICAL FRAMEWORK</h3>

<ul>
<li>GHG Protocol Corporate Accounting Standard</li>
<li>GHG Protocol Scope 3 Standard</li>
<li>IPCC Guidelines for National Greenhouse Gas Inventories</li>
<li>ISO 14064 Greenhouse Gas Standards</li>
</ul>

<h3 style={sectionTitle}>3. EMISSIONS SCOPES</h3>

<p><strong>Scope 1</strong></p>

<ul>
<li>fuel combustion</li>
<li>company vehicles</li>
<li>onsite energy generation</li>
</ul>

<p><strong>Scope 2</strong></p>

<ul>
<li>electricity</li>
<li>steam</li>
<li>heating and cooling</li>
</ul>

<p><strong>Scope 3</strong></p>

<ul>
<li>purchased goods and services</li>
<li>capital goods</li>
<li>transportation and distribution</li>
<li>business travel</li>
<li>waste generated in operations</li>
<li>employee commuting</li>
<li>downstream product use</li>
</ul>


<h3 style={sectionTitle}>CONTACT INFORMATION</h3>

<p>
NettZero Environmental Advisory Technologies Pvt. Ltd.
<br/>
1230 Hubtown Solaris
<br/>
Andheri East
<br/>
Mumbai 400069
<br/>
India
</p>

<p>Email: gautam@nettzero.world</p>

<p style={{marginTop:"40px"}}>
Gautam Shiknis  
Founder  
NettZero Environmental Advisory Technologies Pvt. Ltd.  
1230, Hubtown Solaris, N.S. Phadke Marg, Andheri East, Mumbai  
www.nettzero.world
</p>

</div>

</div>

);

};

export default AgreementPage;